### ISSUE TITLE
Issues when using this provider

### ISSUE THREAD

**Issue by Seb-C** [bytebase/terraform-provider-bytebase#69]
I am trying to import my existing instances into terraform and I ran into several issues:
- The import string is not documented. I had to look into the source code to understand that the id should be `instances/{key}`
- The data source requires a property called `title` that does not seem to be really used, and does not exist in the DB nor in the UI
- When I try to apply any change, I get this error message: `Error: status: 400, body: {"code":3, "message":"data source id is required", "details":[]}`. I tried to add an explicit ID in my configuration as well as directly into the state, but I could not fix this one.

**Comment by ecmadao** [comment]
Thanks for your feedback! We have several API changes, I'll check and update the provider later.

**Comment by ecmadao** [comment]
Hi @Seb-C,
The issue is fixed and the provider is upgraded to 1.0.0, please use it with the [newest Bytebase](https://github.com/bytebase/bytebase/releases/tag/2.22.3)
You can follow the [examples](https://github.com/bytebase/terraform-provider-bytebase/tree/main/examples)
Thanks.

**Comment by Seb-C** [comment]
@ecmadao Thanks. I tested it, but I'm still having issues with it. The data source model in terraform and in ByteBase seems to not be in sync, because the `database`, `ssl_ca` and `password` properties are never in the tf state, which results in terraform trying to change the data source every time, even if there is no actual difference.

**Comment by ecmadao** [comment]
Some sensitive fields like `password` are input-only in Bytebase API, so the sensitive fields in the returned data for GET data-source are empty, that's why the terraform provide always treats it as a changed resource (the API returns empty, but it has value in the local state) @Seb-C

**Comment by ecmadao** [comment]
@Seb-C  Thanks, this inspired me. I checked the [source code](https://github.com/hashicorp/terraform-provider-aws/blob/34b360f2fa5061d0def6381af746ea2dd6d8f2db/internal/service/dms/endpoint.go#L1580) of AWS terraform provider, looks like it's the only dirty way to handle it.
I created a PR to resolve this, and you can try the `v1.0.2` later

**Comment by ecmadao** [comment]
1.0.2 is released https://registry.terraform.io/providers/bytebase/bytebase/latest

**Comment by Seb-C** [comment]
Thanks! It seems to work better now.
